### PR TITLE
Fix a bug that current time can go backwards when playing a video

### PR DESCRIPTION
**Pull request by akshayanv**

### CODE REVIEW

**Comment by akshayanv** [comment]
Just for the record for future:

This CL contains changes that some how got missed in https://github.com/nv-chromium/chromium-crosswalk/commit/8ce070b1837300d4eb2ce3382da5032ff97a9ea6 (nv-xwalk-17) though had got in https://github.com/nv-chromium/chromium-crosswalk/commit/564fbd996b6d8945fd10e6e056be01fbece13935 (nv-chromium51 - no more used for production)

**Comment by akshayanv** [comment]
Sri,

Dont merge this right now.. I am looking at the newest chromium checkout and this change doesn't exist there. Looking more into it.

Wait please

**Comment by akshayanv** [comment]
Oh no no.

No worries. The change can be seen in the file @

https://cs.chromium.org/chromium/src/content/renderer/media/android/webmediaplayer_android.cc?rcl=0&l=830

which is TOT.

Sorry for the confusion. I forgot that my local checkout of chromium was for custom webview v45 solution.

Sorry for the confusion.

**Review by srikumarb — APPROVED** [review]

**Comment by akshayanv** [comment]
Just for the record, this change is same as from google's change: 
https://codereview.chromium.org/2289543005/patch/120001/130003

**Pull request merged**
